[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "main01a"
path = "src/main01a.rs"

[[bin]]
name = "main01b"
path = "src/main01b.rs"